### ISSUE TITLE
Default log level seems to have changed

### ISSUE THREAD

**Issue by ch-zacmo** [ekarak/knx#5]
The default log level should be "info" as per the [comment](https://github.com/ekarak/knx/blob/master/README-API.md) say , but I now get warn message.

**Comment by robertsLando** [comment]
@ch-zacmo Is this relative to the TS rewrite?

**Comment by robertsLando** [comment]
Does it appear also in the ts rewrite? I cannot reproduce it

**Comment by ch-zacmo** [comment]
It will probably. It is very specific as you need ETS to be opened and making SEARCH_REQUEST for this to show.
